// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-integrity-alerts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { integrityAlerts } from "npm:@/data/mockData";
var list_integrity_alerts_default = defineTool({
  name: "list_integrity_alerts",
  title: "List invoice integrity alerts",
  description: "Return open invoice integrity alerts (phantom vendors, duplicates, split invoices, mandate fraud).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(integrityAlerts, null, 2) }],
    structuredContent: { alerts: integrityAlerts }
  })
});

// src/lib/mcp/tools/list-price-drift.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { priceDriftItems } from "npm:@/data/mockData";
var list_price_drift_default = defineTool2({
  name: "list_price_drift",
  title: "List price drift items",
  description: "Return commodities with unit-price drift vs 90-day average. Optionally filter by status (alert >5%, warning 2\u20135%, stable <2%).",
  inputSchema: {
    status: z.enum(["alert", "warning", "stable"]).optional().describe("Filter by drift status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status }) => {
    const items = status ? priceDriftItems.filter((i) => i.status === status) : priceDriftItems;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { items }
    };
  }
});

// src/lib/mcp/tools/list-arbitrage.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { arbitrageOpportunities } from "npm:@/data/mockData";
var list_arbitrage_default = defineTool3({
  name: "list_arbitrage_opportunities",
  title: "List vendor arbitrage opportunities",
  description: "Return lazy-tax arbitrage opportunities across vendors. Each item includes bestPrice, currentPrice, lazyTax, monthlySavings and annualSavings.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      { type: "text", text: JSON.stringify(arbitrageOpportunities, null, 2) }
    ],
    structuredContent: { opportunities: arbitrageOpportunities }
  })
});

// src/lib/mcp/tools/spend-summary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import {
  spendByCategory,
  vendorMonthlySpend,
  vendorConsolidation,
  summaryStats
} from "npm:@/data/mockData";
var spend_summary_default = defineTool4({
  name: "get_spend_summary",
  title: "Get spend summary",
  description: "Return the top-level spend summary: total anomalies, lazy tax, vendor bloat, potential savings, spend by category, and vendor monthly spend.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const payload = {
      summary: summaryStats,
      spendByCategory,
      vendorMonthlySpend,
      vendorConsolidation
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gzybnejswaftyejlcfrv";
var mcp_default = defineMcp({
  name: "strategic-intelligence-mcp",
  title: "Strategic Intelligence",
  version: "0.1.0",
  instructions: "Tools for the Strategic Intelligence procurement dashboard. Query invoice integrity alerts, price drift, vendor arbitrage opportunities, and top-level spend summary.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_integrity_alerts_default, list_price_drift_default, list_arbitrage_default, spend_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
